-- vim.cmd.colorscheme "iceberg"
--
-- vim.cmd.colorscheme "nord"
--
-- vim.cmd.colorscheme "edge"
--
-- vim.cmd.colorscheme "nightfox"
-- vim.cmd.colorscheme "nordfox"
-- vim.cmd.colorscheme "terafox"
-- vim.cmd.colorscheme "duskfox"
--
-- vim.cmd.colorscheme "tokyonight"
--
-- vim.cmd.colorscheme "lucario"
--
-- vim.cmd.colorscheme "hybrid"
--
-- vim.cmd.colorscheme "jellybeans"
--
-- vim.cmd.colorscheme "pinkmare"
--
-- vim.cmd.colorscheme "hatsunemiku"
--
-- vim.cmd.colorscheme "catppuccin"
vim.cmd.colorscheme "kanagawa"
