# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
  # - repo: https://gitlab.com/pablodiehl/pre-commit-lua-formatter.git
  #   rev: v1.0.0
  #   hooks:
  #     - id: lua-formatter

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black"]
  #       additional_dependencies:
  #         - toml
