-- local status, efmls = pcall(require, "efmls-configs")
-- if not status then return end
--
--
-- local function on_attach(client)
--   print('Attached to ' .. client.name)
-- end
--
-- efmls.init {
--   -- Your custom attach function
--   on_attach = on_attach,
--
--   -- Enable formatting provided by efm langserver
--   init_options = {
--     documentFormatting = true,
--   },
-- }
--
-- local black = require 'efmls-configs.formatters.black'
-- local flake8 = require 'efmls-configs.linters.flake8'
-- efmls.setup({
--   python = {
--     linter = flake8,
--     formatter = { black },
--   },
-- })
