[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <Leader> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'szkny/SplitTerm'
on_ft = ['python']

[[plugins]]
repo = 'szkny/Ipython'
on_ft = ['python']
hook_add = '''
  nmap  <leader>ip  :Ipython<CR>
  vmap  <leader>ip  :VIpython<CR>
'''
