
[[plugins]]
repo = 'szkny/SplitTerm'
on_ft = ['python']

# [[plugins]]
# repo = 'vim-scripts/vim-auto-save'
# on_event = 'InsertLeave' 
# hook_add= '''
#   let g:auto_save = 1
#   let g:auto_save_no_updatetime = 5
#   let g:auto_save_in_insert_mode = 0
# ''' 

# syntax file type toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html']
hook_add = '''
  let g:closetag_filenames = '*.html,*.xhtml'
'''

