[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'

[[plugins]]
repo = 'szkny/SplitTerm'
on_ft = ['python']

[[plugins]]
repo = 'szkny/Ipython'
on_ft = ['python']
hook_add = '''
  nmap  <leader>ip  :Ipython<CR>
  vmap  <leader>ip  :VIpython<CR>
'''

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
on_event = 'InsertLeave' 
hook_source = '''
  let g:auto_save = 1
  let g:auto_save_no_updatetime = 1
  let g:auto_save_in_insert_mode = 0
''' 

# syntax file type toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
