[ai]
rules = ""

[server]
browser = "default"
follow_symlink = false

[formatting]
line_length = 99

[language_servers.pylsp]
enable_pydocstyle = false
enable_mypy = true
enabled = true
enable_pyflakes = false
enable_pylint = false
enable_flake8 = false
enable_ruff = true

[completion]
activate_on_typing = true
copilot = false

[runtime]
auto_instantiate = true
auto_reload = "off"
reactive_tests = true
output_max_bytes = 8000000
watcher_on_save = "lazy"
on_cell_change = "lazy"
std_stream_max_bytes = 1000000

[display]
default_width = "medium"
theme = "light"
code_editor_font_size = 14
cell_output = "above"
dataframes = "rich"
default_table_page_size = 10

[package_management]
manager = "uv"

[experimental]

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[snippets]
include_default_snippets = true
custom_paths = []

[keymap]
preset = "default"
[keymap.overrides]
