[ai]
rules = ""

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[experimental]

[formatting]
line_length = 79

[keymap]
preset = "default"
[keymap.overrides]

[runtime]
output_max_bytes = 8000000
auto_reload = "off"
reactive_tests = true
auto_instantiate = true
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
on_cell_change = "autorun"

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[package_management]
manager = "uv"

[language_servers.pylsp]
enable_pyflakes = false
enable_pylint = false
enable_ruff = true
enabled = true
enable_pydocstyle = false
enable_flake8 = false
enable_mypy = true

[display]
theme = "light"
default_width = "medium"
cell_output = "above"
code_editor_font_size = 14
dataframes = "rich"
default_table_page_size = 10

[completion]
activate_on_typing = true
copilot = false
