[ai]
rules = ""
mode = "manual"

[ai.bedrock]

[ai.anthropic]

[ai.google]

[ai.open_ai]

[diagnostics]

[experimental]

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[language_servers.pylsp]
enable_pydocstyle = false
enable_pyflakes = false
enable_pylint = false
enable_mypy = true
enable_ruff = true
enable_flake8 = false
enabled = true

[language_servers.ty]

[formatting]
line_length = 99

[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[display]
default_table_page_size = 10
default_table_max_columns = 50
reference_highlighting = false
dataframes = "rich"
code_editor_font_size = 14
theme = "light"
default_width = "medium"
cell_output = "below"

[package_management]
manager = "uv"

[completion]
activate_on_typing = true
copilot = "github"

[snippets]
include_default_snippets = true
custom_paths = []

[runtime]
default_sql_output = "auto"
output_max_bytes = 8000000
on_cell_change = "autorun"
watcher_on_save = "lazy"
auto_instantiate = false
auto_reload = "autorun"
std_stream_max_bytes = 1000000
reactive_tests = true
default_auto_download = []

[server]
browser = "default"
follow_symlink = false
